config/routes.rb
Rails.application.routes.draw do
  root "departs#index"

  resources :departs do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/depart.rb
class Depart < ApplicationRecord
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :depart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departs_controller.rb
class DepartsController < ApplicationController
  before_action :set_depart, only: [:show, :edit, :update, :destroy]
  def index
    @departs = Depart.all
  end

  def show
  end

  def new
    @depart = Depart.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @depart = Depart.new(depart_params)

    if @depart.save 
      redirect_to departs_path
    else 
      render :new
    end
  end

  def update
    if @depart.update(depart_params)
      redirect_to depart_path(@depart)
    else
      render :edit
    end
  end

  def destroy
    @depart.destroy
    redirect_to departs_path
  end

  private
    def depart_params
      params.required(:depart).permit(:dpt_name)
    end

    def set_depart
      @depart = Depart.find(params[:id])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_depart
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def index
    @item = @depart.items
  end

  def show
  end

  def new
    @item = @depart.items.new
    render partial: "form"
  end

  def create
    @item = @depart.items.new(item_params)

    if @item.save
      redirect_to sub_items_path(@item)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to depart_item_path(@depart, @item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to depart_items_path(@item)
  end

  private
    def set_depart
      @depart = Depart.find(params[:depart_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.required(:item).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departs_helper.rb
module DepartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departs/_form.html.erb
<h1><%= @depart.id ? "Edit Depart" : "New Depart" %></h1>
<hr />
<%= form_for @depart do |f| %>
  <%= f.label :dpt_name %>
  <%= f.text_field :dpt_name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/departs/edit.html.erb
<h1>Departs#edit</h1>
<p>Find me in app/views/departs/edit.html.erb</p>

app/views/departs/index.html.erb
<h1>Click a Department to View Content</h1>
<%= link_to "Create a new department", new_depart_path %>

<h3><%= @departs.length === 0 ? "No departments added" : "" %></h3>

<ul>
  <% @departs.each do |depart| %>
    <li><%= link_to depart.name, depart_path(depart) %></li>
  <% end %>
  </ul>

app/views/departs/new.html.erb
<h1>Departs#new</h1>
<p>Find me in app/views/departs/new.html.erb</p>

app/views/departs/show.html.erb
<h1><%= @depart.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to "View Items", depart_items_path(@depart) %>
<br />
<%= link_to "Edit Depart", edit_depart_path(@sub) %>
<br />
<%= link_to "Delete Depart", depart_path(@sub), method: :delete %>

app/views/items/_form.html.erb
<h1><%= @item.id ? "Edit Item" : "Create Item" %></h1>
<hr />
<%= form_for [@depart, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <br />
  <%= f.label :description %>
  <%= f.text_area :description, required: true %>
  <%= f.submit %>
  <% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Click an Item to View Description</h1>
<%= link_to "Create a new Item", new_depart_item_path(@depart) %>
<ul>
  <% @items.eqach do |item| %>
    <li><%= link_to item.name, depart_item_path(@depart, item)%></li>
  <% end %>
</ul>  

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @depart.name %> - <%= @item.name %></h1>
<p><%= @item.description %></p>
<%= link_to "Edit Item", edit_depart_item_path(@depart, @item) %>
<%= link_to "Delete Item", depart_item_path(@depart, @item) %>
<%= link_to "Back to Items", depart_items_path(@depart) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dpt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>